name: Build & Deploy Godot HTML5 Debug Build

on:
  workflow_dispatch:   # manual trigger
  push:
    branches: [main]   # or your dev branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Build Godot HTML5 Export
      # (This uses the marketplace action you linked)
      - name: Build Godot HTML5 export
        uses: firebelley/godot-export@v6
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
          export_preset: "HTML5"
          output_path: build/web
          cache: true

      # 3️⃣ Prepare debug subfolder
      - name: Prepare /debug site folder
        run: |
          mkdir -p public/debug
          cp -r build/web/* public/debug/
          mv public/debug/index.html public/debug/index.html

      # 4️⃣ Upload artifact for GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      # 5️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
