name: Build & Deploy Godot HTML5 Debug Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3  # Godot 4.3 + export templates

    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Godot 4 export templates manually
      - name: Install Godot 4 export templates
        run: |
          mkdir -p ~/.local/share/godot/templates/4.3.stable
          wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
          unzip Godot_v4.3-stable_export_templates.tpz -d ~/.local/share/godot/templates/4.3.stable

      - name: Build HTML5 export
        run: |
          mkdir -p build/web
          godot --headless --verbose --export-release "Web" build/web/index.html

      - name: Prepare /debug site folder
        run: |
          mkdir -p public/debug
          cp -r build/web/* public/debug/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
