name: "godot-ci debug export"
on:
  push:
  workflow_dispatch:

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".
permissions:
  contents: write
  id-token: write
  pages: write

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: platformer-v2
  PROJECT_PATH: "."

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-24.04  # Use 24.04 with godot 4
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web/debug
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/debug/index.html"
      - name: Prepare page
        run: |
          mkdir public/debug
          mv "$EXPORT_DIR/web/debug/platformerv2.html public/debug/index.html || true

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public/debug

      - name: Deploy Release to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

