name: "Debug build"

on:
  workflow_dispatch:
  push:
    branches: ["main"] # or another branch if you prefer

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: platformer-v2
  PROJECT_PATH: .

permissions:
  contents: write  # needed to push to gh-pages

jobs:
  build-debug:
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot export templates
        run: |
          mkdir -pv ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable \
             ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Export Debug Web Build
        run: |
          mkdir -pv build/debug
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-debug "Web" "$EXPORT_DIR/debug/index.html"

      - name: Deploy Debug Build to /debug 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages          # Branch your site is published from
          folder: build/debug       # Deploy only this folder
          target-folder: debug      # Upload to /debug/ subfolder
          clean: false              # 👈 Don't delete existing files (main release stays)
          token: ${{ secrets.GITHUB_TOKEN }}
