name: Build & Deploy Godot HTML5 Debug Build

on:
  workflow_dispatch:   # allows manual trigger
  push:
    branches: [main]   # or your dev branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Godot and export templates (abarichello/godot-ci)
      - name: godot-ci
        uses: abarichello/godot-ci@3.6.2-stable
        with:
          version: 4.3
          export-templates: true

      # 3️⃣ Build your Godot project for HTML5
      - name: Build HTML5 export
        run: |
          mkdir -p build/web
          godot --headless --verbose --export-release "HTML5" build/web/index.html

      # 4️⃣ Prepare /debug site folder
      - name: Prepare /debug site folder
        run: |
          mkdir -p public/debug
          cp -r build/web/* public/debug/

      # 5️⃣ Upload artifact for GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      # 6️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
