name: Godot Web Export and Deploy

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write
  pages: write

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: platformer-v2
  PROJECT_PATH: "."

jobs:
  deploy-release:
    name: Deploy Release ZIP to Pages
    runs-on: ubuntu-latest
    #needs: export-web  # ensures debug build runs first
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download latest release asset (web*.zip)
        id: download
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          regex: true
          file: "web.*\\.zip"
          token: ${{ secrets.TOKEN }}

      - name: Unzip the HTML5 export
        run: |
          mkdir public
          unzip *.zip -d public
          mv public/platformerv2.html public/index.html || true

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy Release to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
