name: Godot Web Export and Deploy

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write
  pages: write

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: platformer-v2
  PROJECT_PATH: "."

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.4.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Build HTML5 export (Debug)
        run: |
          mkdir -p build/web/debug
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-debug "Web" "$EXPORT_DIR/web/debug/index.html"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-web-debug
          path: build/web/debug

      - name: Install rsync
        run: apt-get update && apt-get install -y rsync

      - name: Deploy Debug Build to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: build/web/debug
          target-folder: debug

      - name: Upload to GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web/debug

  deploy-release:
    name: Deploy Release ZIP to Pages
    runs-on: ubuntu-latest
    needs: export-web  # ensures debug build runs first
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download latest release asset (web*.zip)
        id: download
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          regex: true
          file: "web.*\\.zip"
          token: ${{ secrets.TOKEN }}

      - name: Unzip the HTML5 export
        run: |
          mkdir public
          unzip *.zip -d public
          mv public/platformerv2.html public/index.html || true

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy Release to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
