name: Deploy Godot HTML5 build to GitHub Pages

on:
  workflow_dispatch:   # allows manual trigger
  release:
    types: [published] # runs automatically on new release

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download latest release asset (web*.zip)
        id: download
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          file: "web.*\\.zip"
          token: ${{ secrets.TOKEN }}

      - name: Unzip the HTML5 export
        run: |
          mkdir public
          unzip "${{ steps.download.outputs.asset_path }}" -d public

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
